from __future__ import annotations

CONCEPTS = [
    {
        "id": "java_operators",
        "name": "Java Operators",
        "domain": "programming",
        "description": "Assignment, comparison, and logical operators in introductory Java.",
    },
    {
        "id": "java_arrays",
        "name": "Java Arrays & Indexing",
        "domain": "programming",
        "description": "Zero-based indexing and array bounds.",
    },
    {
        "id": "java_loops",
        "name": "Java Loops",
        "domain": "programming",
        "description": "for/while loop bounds, increment, and termination.",
    },
    {
        "id": "java_variables",
        "name": "Java Variables & Scope",
        "domain": "programming",
        "description": "Declaration, assignment, and lexical scope.",
    },
    {
        "id": "java_booleans",
        "name": "Java Boolean Logic",
        "domain": "programming",
        "description": "&&, ||, short-circuit evaluation.",
    },
    {
        "id": "java_strings",
        "name": "Java Strings",
        "domain": "programming",
        "description": "String identity vs equality.",
    },
    {
        "id": "java_methods",
        "name": "Java Methods",
        "domain": "programming",
        "description": "Parameters, arguments, and return values.",
    },
    {
        "id": "java_oop",
        "name": "Java Objects & Static",
        "domain": "programming",
        "description": "Instance members vs static members.",
    },
]

MISCONCEPTIONS = [
    {
        "id": "assignment_vs_comparison",
        "name": "Assignment (=) vs comparison (==)",
        "concept_id": "java_operators",
        "description": "Learner treats == as assignment or = as a comparison.",
        "examples": "= copies a value. == asks whether two values are equal.",
        "common_patterns": "says == assigns; uses = inside if conditions; describes comparison as storing",
        "intervention_strategy": "Contrast a tiny assignment statement with a boolean comparison. Never only show the right answer.",
        "assessment_strategy": "Ask what x == 10 returns after int x = 10.",
        "signatures": ["assign", "puts a value", "stores", "sets the variable", "gives a value"],
    },
    {
        "id": "zero_based_indexing",
        "name": "Zero-based indexing",
        "concept_id": "java_arrays",
        "description": "Learner thinks the first element lives at index 1.",
        "examples": "arr[0] is the first element; last index is length - 1.",
        "common_patterns": "first index is 1; last index is length; names[1] is Alice when Alice is first",
        "intervention_strategy": "Show a 3-element array drawn with indexes 0,1,2.",
        "assessment_strategy": "Ask for the index of the first and last elements of a 4-item array.",
        "signatures": ["index 1", "starts at 1", "first is 1", "last is length"],
    },
    {
        "id": "loop_boundary_errors",
        "name": "Loop boundary errors",
        "concept_id": "java_loops",
        "description": "Off-by-one: i <= n vs i < n, or looping length instead of length-1.",
        "examples": "for (int i = 0; i < arr.length; i++) visits every index exactly once.",
        "common_patterns": "i <= array.length; runs n+1 times; misses last item; ArrayIndexOutOfBounds",
        "intervention_strategy": "Trace i on a 3-element array for < vs <=.",
        "assessment_strategy": "Ask how many times a given for-loop body runs.",
        "signatures": ["<= length", "off by one", "runs too many", "includes length", "out of bounds"],
    },
    {
        "id": "pre_vs_post_increment",
        "name": "++i vs i++",
        "concept_id": "java_loops",
        "description": "Learner thinks pre and post increment always have the same value in an expression.",
        "examples": "i++ yields the old value then adds 1. ++i adds 1 then yields the new value.",
        "common_patterns": "both always the same; ++ only used in loops; i++ returns new value",
        "intervention_strategy": "Show int x = 5; print x++ vs ++x.",
        "assessment_strategy": "Given int n = 3; ask the value of n++ used in an expression.",
        "signatures": ["same thing", "both add first", "i++ returns new", "no difference"],
    },
    {
        "id": "variable_scope",
        "name": "Variable scope",
        "concept_id": "java_variables",
        "description": "Learner expects a block-local variable to exist after the block.",
        "examples": "A variable declared inside { } cannot be used after that block.",
        "common_patterns": "still available after loop; can use i after for; inner variable leaks",
        "intervention_strategy": "Draw nested boxes for method vs loop vs if blocks.",
        "assessment_strategy": "Ask whether a loop-declared int i is visible after the loop.",
        "signatures": ["still exists", "outside the loop", "after the block", "visible everywhere"],
    },
    {
        "id": "and_vs_or",
        "name": "&& vs ||",
        "concept_id": "java_booleans",
        "description": "Learner swaps conjunction and disjunction, or ignores short-circuiting.",
        "examples": "&& needs both true. || needs at least one true. Right side may not run.",
        "common_patterns": "&& means or; both needed for ||; always evaluates both sides",
        "intervention_strategy": "Use a door-lock analogy: && is two locks, || is two doors.",
        "assessment_strategy": "Evaluate true && false and false || true.",
        "signatures": ["&& means or", "both for ||", "always checks both", "or requires both"],
    },
    {
        "id": "string_equals_vs_eq",
        "name": "String == vs equals()",
        "concept_id": "java_strings",
        "description": "Learner uses == to compare String contents.",
        "examples": "== compares references. equals() compares characters.",
        "common_patterns": "== compares text; equals is the same as ==; new String still ==",
        "intervention_strategy": "Show two new String(\"hi\") objects: == is false, equals is true.",
        "assessment_strategy": "Ask the result of new String(\"a\") == new String(\"a\").",
        "signatures": ["== compares text", "same as equals", "compares letters with ==", "content with =="],
    },
    {
        "id": "parameters_vs_arguments",
        "name": "Method parameters vs arguments",
        "concept_id": "java_methods",
        "description": "Learner mixes the names of placeholders in a signature with values at the call site.",
        "examples": "Parameters are declared in the method. Arguments are the values you pass in.",
        "common_patterns": "parameter is the value passed; argument is in the signature",
        "intervention_strategy": "Label void greet(String name) vs greet(\"Ada\").",
        "assessment_strategy": "In void add(int a, int b) called as add(2, 3), name a and 2.",
        "signatures": ["parameter is passed", "argument in signature", "they are the same name"],
    },
    {
        "id": "return_value",
        "name": "Return value misconceptions",
        "concept_id": "java_methods",
        "description": "Learner thinks a method always prints, or ignores that return must be used by the caller.",
        "examples": "return hands a value back. It does not print unless the caller prints it.",
        "common_patterns": "return prints; void can return a number; result appears automatically",
        "intervention_strategy": "Contrast System.out.println vs return, then show int y = f();",
        "assessment_strategy": "Ask what a caller must do to see a returned int.",
        "signatures": ["return prints", "shows on screen", "void returns", "automatically displayed"],
    },
    {
        "id": "static_vs_instance",
        "name": "Static vs non-static",
        "concept_id": "java_oop",
        "description": "Learner calls instance methods from static main without an object, or thinks static belongs to each object.",
        "examples": "static belongs to the class. Instance members need an object.",
        "common_patterns": "call instance from main; static per object; new not needed",
        "intervention_strategy": "Show Counter.count vs player.score.",
        "assessment_strategy": "Ask whether main can call a non-static method directly.",
        "signatures": ["from main without object", "static per object", "no new needed", "belongs to every instance"],
    },
]

QUESTIONS = [
    {
        "id": "q_eq_meaning",
        "concept_id": "java_operators",
        "prompt": "What does == mean in Java?",
        "correct_answer": "It compares two values for equality.",
        "difficulty": "intro",
        "misconceptions": ["assignment_vs_comparison"],
        "is_reassessment": False,
        "diagnostic_followup": "In Java, which symbol actually copies a value into a variable: = or ==?",
    },
    {
        "id": "q_eq_result",
        "concept_id": "java_operators",
        "prompt": "If int x = 10, what does x == 10 return?",
        "correct_answer": "true",
        "difficulty": "intro",
        "misconceptions": ["assignment_vs_comparison"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_if_assign",
        "concept_id": "java_operators",
        "prompt": "Why is `if (x = 5)` usually a compile error in Java when x is int?",
        "correct_answer": "Because = assigns and yields an int, while if requires a boolean. Use == to compare.",
        "difficulty": "intro",
        "misconceptions": ["assignment_vs_comparison"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_first_index",
        "concept_id": "java_arrays",
        "prompt": "In Java, what is the index of the first element of array names?",
        "correct_answer": "0",
        "difficulty": "intro",
        "misconceptions": ["zero_based_indexing"],
        "is_reassessment": False,
        "diagnostic_followup": "If names has 3 items, what is the index of the last item?",
    },
    {
        "id": "q_last_index",
        "concept_id": "java_arrays",
        "prompt": "A Java array has length 4. What is the index of its last element?",
        "correct_answer": "3",
        "difficulty": "intro",
        "misconceptions": ["zero_based_indexing"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_loop_bound",
        "concept_id": "java_loops",
        "prompt": "How many times does `for (int i = 0; i < 3; i++)` run its body?",
        "correct_answer": "3",
        "difficulty": "intro",
        "misconceptions": ["loop_boundary_errors"],
        "is_reassessment": False,
        "diagnostic_followup": "Would `i <= 3` run more times, fewer times, or the same?",
    },
    {
        "id": "q_loop_length",
        "concept_id": "java_loops",
        "prompt": "For int[] a = {2,4,6}, is `for (int i = 0; i <= a.length; i++)` safe? Why?",
        "correct_answer": "No. i <= a.length uses index 3, which is out of bounds. Use i < a.length.",
        "difficulty": "intro",
        "misconceptions": ["loop_boundary_errors"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_postinc",
        "concept_id": "java_loops",
        "prompt": "int n = 3; What value is used in the expression n++ the first time, and what is n afterward?",
        "correct_answer": "The expression uses 3, then n becomes 4.",
        "difficulty": "intro",
        "misconceptions": ["pre_vs_post_increment"],
        "is_reassessment": False,
        "diagnostic_followup": "Does ++n use the new value or the old value in the same expression?",
    },
    {
        "id": "q_preinc",
        "concept_id": "java_loops",
        "prompt": "int n = 3; What does ++n evaluate to?",
        "correct_answer": "4",
        "difficulty": "intro",
        "misconceptions": ["pre_vs_post_increment"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_scope",
        "concept_id": "java_variables",
        "prompt": "After `for (int i = 0; i < 3; i++) { }`, can you print i in the next line of the same method?",
        "correct_answer": "No. i exists only inside the for-loop.",
        "difficulty": "intro",
        "misconceptions": ["variable_scope"],
        "is_reassessment": False,
        "diagnostic_followup": "Where would you declare i if you need it after the loop?",
    },
    {
        "id": "q_scope_if",
        "concept_id": "java_variables",
        "prompt": "int x is declared inside an if block. Can a later else-less statement in the same method use x?",
        "correct_answer": "No. x is scoped to the if block.",
        "difficulty": "intro",
        "misconceptions": ["variable_scope"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_and",
        "concept_id": "java_booleans",
        "prompt": "What is the result of `true && false` in Java?",
        "correct_answer": "false",
        "difficulty": "intro",
        "misconceptions": ["and_vs_or"],
        "is_reassessment": False,
        "diagnostic_followup": "Does || require both sides to be true?",
    },
    {
        "id": "q_or",
        "concept_id": "java_booleans",
        "prompt": "What is the result of `false || true`?",
        "correct_answer": "true",
        "difficulty": "intro",
        "misconceptions": ["and_vs_or"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_string_eq",
        "concept_id": "java_strings",
        "prompt": "Should you use == or equals() to check if two Java strings have the same characters?",
        "correct_answer": "equals()",
        "difficulty": "intro",
        "misconceptions": ["string_equals_vs_eq"],
        "is_reassessment": False,
        "diagnostic_followup": "What does == compare for objects?",
    },
    {
        "id": "q_string_new",
        "concept_id": "java_strings",
        "prompt": "Does `new String(\"hi\") == new String(\"hi\")` return true?",
        "correct_answer": "false",
        "difficulty": "intro",
        "misconceptions": ["string_equals_vs_eq"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_params",
        "concept_id": "java_methods",
        "prompt": "In `void greet(String name)` called as `greet(\"Ada\")`, what is the parameter and what is the argument?",
        "correct_answer": "Parameter is name. Argument is \"Ada\".",
        "difficulty": "intro",
        "misconceptions": ["parameters_vs_arguments"],
        "is_reassessment": False,
        "diagnostic_followup": "",
    },
    {
        "id": "q_params2",
        "concept_id": "java_methods",
        "prompt": "Where are arguments written: in the method header or at the call site?",
        "correct_answer": "At the call site.",
        "difficulty": "intro",
        "misconceptions": ["parameters_vs_arguments"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_return",
        "concept_id": "java_methods",
        "prompt": "Does `return x;` print x to the console by itself?",
        "correct_answer": "No. return gives x back to the caller. The caller may print it.",
        "difficulty": "intro",
        "misconceptions": ["return_value"],
        "is_reassessment": False,
        "diagnostic_followup": "",
    },
    {
        "id": "q_return2",
        "concept_id": "java_methods",
        "prompt": "How does a caller use the int returned by `int score()`?",
        "correct_answer": "Assign it or pass it, e.g. int s = score();",
        "difficulty": "intro",
        "misconceptions": ["return_value"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
    {
        "id": "q_static",
        "concept_id": "java_oop",
        "prompt": "Can public static void main call a non-static method play() directly as play()?",
        "correct_answer": "No. Create an object first, then call object.play().",
        "difficulty": "intro",
        "misconceptions": ["static_vs_instance"],
        "is_reassessment": False,
        "diagnostic_followup": "",
    },
    {
        "id": "q_static2",
        "concept_id": "java_oop",
        "prompt": "Does a static field belong to each object or to the class?",
        "correct_answer": "To the class. All instances share it.",
        "difficulty": "intro",
        "misconceptions": ["static_vs_instance"],
        "is_reassessment": True,
        "diagnostic_followup": "",
    },
]

LABELED_EVAL = [
    {
        "question": "What does == mean in Java?",
        "correct_answer": "It compares two values for equality.",
        "student_answer": "It assigns a value to a variable.",
        "reasoning": "== puts the value into the variable.",
        "code": "",
        "label": "assignment_vs_comparison",
    },
    {
        "question": "Index of first array element?",
        "correct_answer": "0",
        "student_answer": "1",
        "reasoning": "Counting starts at 1.",
        "code": "",
        "label": "zero_based_indexing",
    },
    {
        "question": "for (int i = 0; i <= a.length; i++) safe?",
        "correct_answer": "No, out of bounds.",
        "student_answer": "Yes it visits every element including the last.",
        "reasoning": "We need <= to include the last index.",
        "code": "for (int i = 0; i <= a.length; i++)",
        "label": "loop_boundary_errors",
    },
    {
        "question": "n++ vs ++n",
        "correct_answer": "n++ uses old value.",
        "student_answer": "They are always the same.",
        "reasoning": "Both just add one.",
        "code": "",
        "label": "pre_vs_post_increment",
    },
    {
        "question": "Can you use loop i after the for header declaration?",
        "correct_answer": "No.",
        "student_answer": "Yes, i still exists.",
        "reasoning": "The method can see it.",
        "code": "",
        "label": "variable_scope",
    },
    {
        "question": "true && false",
        "correct_answer": "false",
        "student_answer": "true because one side is true",
        "reasoning": "&& is like or.",
        "code": "",
        "label": "and_vs_or",
    },
    {
        "question": "Compare string contents",
        "correct_answer": "equals()",
        "student_answer": "==",
        "reasoning": "== checks the letters.",
        "code": "if (a == b)",
        "label": "string_equals_vs_eq",
    },
    {
        "question": "parameter vs argument",
        "correct_answer": "Parameter in header, argument at call.",
        "student_answer": "The parameter is the value you pass in.",
        "reasoning": "",
        "code": "",
        "label": "parameters_vs_arguments",
    },
    {
        "question": "Does return print?",
        "correct_answer": "No.",
        "student_answer": "Yes, return shows the value on screen.",
        "reasoning": "",
        "code": "return x;",
        "label": "return_value",
    },
    {
        "question": "Call instance method from main",
        "correct_answer": "Need an object.",
        "student_answer": "Just call play(); from main.",
        "reasoning": "main is in the same class.",
        "code": "public static void main(String[] args) { play(); }",
        "label": "static_vs_instance",
    },
    {
        "question": "What does == mean in Java?",
        "correct_answer": "Compares two values.",
        "student_answer": "It checks if two values are equal.",
        "reasoning": "Like asking whether they match.",
        "code": "",
        "label": None,
    },
]
